# Generated by Django 5.2.16 on 2026-08-05 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Kan VKV Nieuws lezen'), ('schrijven', 'Kan berichten schrijven en bewerken'), ('verzenden', 'Kan berichten naar EVE-mail en Discord sturen')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(help_text='Bijvoorbeeld je characternaam.', max_length=255, unique=True, verbose_name='Naam')),
                ('kleur', models.CharField(default='#ffe400', help_text='Waarin de naam in de EVE-mail komt te staan.', max_length=7, verbose_name='Kleur van de naam')),
                ('organisatie', models.CharField(blank=True, help_text='Komt achter de naam met een streepje ertussen. Mag leeg.', max_length=255, verbose_name='Organisatie')),
                ('kleur_organisatie', models.CharField(default='#ff8c00', max_length=7, verbose_name='Kleur van de organisatie')),
                ('standaard', models.BooleanField(default=False, help_text='Staat vast voorgeselecteerd bij een nieuw bericht.', verbose_name='standaard')),
            ],
            options={
                'verbose_name': 'auteur',
                'verbose_name_plural': 'auteurs',
                'ordering': ('-standaard', 'naam'),
            },
        ),
        migrations.CreateModel(
            name='Instellingen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_webhook', models.URLField(blank=True, help_text='De webhook-URL van het kanaal waar de berichten in moeten komen. Leeg laten zet Discord uit.', max_length=500, verbose_name='Discord-webhook')),
                ('logo', models.ImageField(blank=True, help_text='Komt rechts op de voorbeeldkaart voor Discord. Vierkant werkt het best; een PNG met doorzichtige achtergrond is het mooist.', upload_to='vkvnieuws/', verbose_name='Logo')),
                ('discord_stijl', models.CharField(choices=[('voorbeeld', 'Voorbeeldkaart met link naar de site'), ('tekst', 'De hele nieuwsbrief als tekst'), ('tekst_plaatje', 'De hele nieuwsbrief plus een gekleurde afbeelding')], default='voorbeeld', help_text='Een voorbeeldkaart is een aankondiging: titel, de eerste zinnen en een link naar de site. De hele nieuwsbrief kan ook, maar die wordt opgeknipt — Discord staat maar 2.000 tekens per bericht toe.', max_length=20, verbose_name='Wat er op Discord komt')),
                ('bijgewerkt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'instellingen',
                'verbose_name_plural': 'instellingen',
            },
        ),
        migrations.CreateModel(
            name='Bericht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onderwerp', models.CharField(max_length=1000)),
                ('tekst', models.TextField(help_text='Opgemaakte tekst in de opmaak die EVE-mail kent.')),
                ('link_systemen', models.BooleanField(default=True, help_text='Namen als HB-5L3 worden in de EVE-mail een link naar het systeem.', verbose_name='Systeemnamen klikbaar maken')),
                ('aangemaakt', models.DateTimeField(auto_now_add=True)),
                ('bijgewerkt', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(help_text='De Alliance Auth-gebruiker die dit bericht schreef. Wordt vanzelf ingevuld.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vkvberichten', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
                ('ondertekend_door', models.ForeignKey(blank=True, help_text='De naam die onder het bericht komt te staan. Leeg laten gebruikt de gebruikersnaam hierboven.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vkvnieuws.auteur', verbose_name='Ondertekend door')),
            ],
            options={
                'verbose_name': 'bericht',
                'verbose_name_plural': 'berichten',
                'ordering': ('-aangemaakt',),
            },
        ),
        migrations.CreateModel(
            name='StandaardOntvanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort', models.CharField(choices=[('corporation', 'Corporatie'), ('alliance', 'Alliantie'), ('character', 'Character'), ('mailing_list', 'Mailinglijst')], default='corporation', max_length=20)),
                ('eve_id', models.BigIntegerField()),
                ('naam', models.CharField(max_length=255)),
                ('standaard', models.BooleanField(default=False, help_text='Staat aangevinkt bij een nieuw bericht.', verbose_name='standaard')),
            ],
            options={
                'verbose_name': 'vaste ontvanger',
                'verbose_name_plural': 'vaste ontvangers',
                'ordering': ('-standaard', 'naam'),
                'unique_together': {('soort', 'eve_id')},
            },
        ),
        migrations.CreateModel(
            name='Verzending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanaal', models.CharField(choices=[('evemail', 'EVE-mail'), ('discord', 'Discord')], max_length=20)),
                ('gelukt', models.BooleanField(default=False)),
                ('tijdstip', models.DateTimeField(auto_now_add=True)),
                ('afzender', models.CharField(blank=True, max_length=255)),
                ('toelichting', models.TextField(blank=True)),
                ('bericht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verzendingen', to='vkvnieuws.bericht')),
            ],
            options={
                'verbose_name': 'verzending',
                'verbose_name_plural': 'verzendingen',
                'ordering': ('-tijdstip',),
            },
        ),
        migrations.CreateModel(
            name='Ontvanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort', models.CharField(choices=[('corporation', 'Corporatie'), ('alliance', 'Alliantie'), ('character', 'Character'), ('mailing_list', 'Mailinglijst')], default='corporation', max_length=20)),
                ('eve_id', models.BigIntegerField()),
                ('naam', models.CharField(blank=True, help_text='Alleen om te tonen; ESI werkt op id.', max_length=255)),
                ('bericht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontvangers', to='vkvnieuws.bericht')),
            ],
            options={
                'verbose_name': 'ontvanger',
                'verbose_name_plural': 'ontvangers',
                'unique_together': {('bericht', 'soort', 'eve_id')},
            },
        ),
    ]
