# Generated by Django 5.2.16 on 2026-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkvnieuws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bericht',
            name='nummer',
            field=models.PositiveIntegerField(blank=True, help_text='Het nummer van deze editie. Laat leeg bij een nieuw bericht; dan pakt de plugin het eerstvolgende.', null=True, unique=True, verbose_name='Editie'),
        ),
    ]
