# Generated by Django 5.2.16 on 2026-08-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkvnieuws', '0003_nummers_invullen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piloot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_id', models.BigIntegerField(unique=True, verbose_name='Character-id')),
                ('naam', models.CharField(max_length=255, verbose_name='Naam')),
                ('bron', models.CharField(choices=[('corp', 'Ledenlijst van de corp'), ('auth', 'Gekoppeld in Alliance Auth'), ('hand', 'Zelf toegevoegd')], default='hand', max_length=10, verbose_name='Herkomst')),
                ('linken', models.BooleanField(default=True, help_text='Uitzetten voor een naam die ook een gewoon woord is; die zou anders midden in een zin oplichten.', verbose_name='Automatisch linken')),
                ('bijgewerkt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'piloot',
                'verbose_name_plural': 'piloten',
                'ordering': ('naam',),
            },
        ),
        migrations.AddField(
            model_name='bericht',
            name='link_piloten',
            field=models.BooleanField(default=True, help_text='Namen uit de pilotenlijst worden een link naar het karakter.', verbose_name='Pilotennamen klikbaar maken'),
        ),
    ]
