# Generated by Django 5.2.16 on 2026-08-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkvnieuws', '0005_pilootkleur_lichtblauw'),
    ]

    operations = [
        migrations.AddField(
            model_name='instellingen',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Staat je logo al ergens op internet, vul dan hier het adres in in plaats van te uploaden. Handig als de mediamap van de server niet publiek is — dan blijft een upload namelijk een gebroken plaatje.', max_length=500, verbose_name='Logo-adres'),
        ),
        migrations.AlterField(
            model_name='instellingen',
            name='logo',
            field=models.ImageField(blank=True, help_text='Komt op de kaarten en op de voorbeeldkaart voor Discord. Vierkant werkt het best; een PNG met doorzichtige achtergrond is het mooist.', upload_to='vkvnieuws/', verbose_name='Logo'),
        ),
    ]
