# Generated by Django 5.2.16 on 2026-08-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkvnieuws', '0006_instellingen_logo_url_alter_instellingen_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instellingen',
            name='discord_vermelding',
            field=models.CharField(choices=[('geen', 'Niemand aantikken'), ('everyone', '@everyone'), ('here', '@here — alleen wie online is')], default='everyone', help_text='Komt op een eigen regel boven de nieuwsbrief. Alleen bij de eerste keer dat een bericht op Discord komt — stuur je hem nog eens, dan blijft de melding uit.', max_length=10, verbose_name='Wie aantikken op Discord'),
        ),
    ]
